nordnet/ui

- .travis.yml
- package.json
- yarn.lock
@iamstarkov please help me with tokens tomorrow.
> ci: add publishing to github pages

- src/Atoms/Separator/Separator.stories.tsx
- src/Atoms/Separator/Separator.tsx
- src/Atoms/Separator/Separator.types.ts
- src/Atoms/Separator/index.ts
- src/index.ts
* Vertical and horizontal separator created
**Vertical**
**Horizontal**
> feat: separator

- src/Atoms/Currency/Currency.stories.tsx
- src/Atoms/Currency/Currency.tsx
- src/Atoms/Currency/Currency.types.ts
- src/Atoms/Currency/index.ts
Initial implementation for Currency component.
> feat: currency MVP

- src/Atoms/Development/Development.stories.tsx
- src/Atoms/Development/Development.tsx
- src/Atoms/Development/Development.types.ts
- src/Atoms/Development/index.ts
- src/Atoms/Text/Text.types.ts
Initial implementation for development component
> feat: development

- src/Molecules/Button/Button.tsx
- src/__snapshots__/storyshots.test.ts.snap
- src/common/NormalizedElements/NormalizedButton.tsx
- src/common/NormalizedElements/index.ts
The small amount of actual elements targeted by our trimmed normalize can live in a global css in my opinion
> feat: normalize

- src/Atoms/Flag/Flag.types.ts
> Dnd 36 contract

- src/Molecules/TitledCard/TitledCard.types.ts
> feat: contract for titledCard

- src/Atoms/Spinner/Spinner.types.ts
> feat: contract for spinner

- src/Molecules/ListWithTitles/ListWithTitles.tsx
- src/__snapshots__/storyshots.test.ts.snap
> Dnd 149 change default color list title

- src/Atoms/Table/Tr/Tr.tsx
- src/Atoms/Table/Tr/Tr.types.ts
* feat: added classname as prop to the Tr
> DND-170-Add-classname-to-Tr

- src/Atoms/Number/Number.stories.tsx
- src/Atoms/Number/Number.tsx
- src/Atoms/Number/Number.types.ts
- src/__snapshots__/storyshots.test.ts.snap
Mostly ported from https://github.com/nordnet/nordnet-component-kit/blob/master/src/components/number/number.jsx
> feat(Number): implement ticks

- src/Molecules/Button/Button.stories.tsx
- src/Molecules/Button/Button.tsx
- src/__snapshots__/storyshots.test.ts.snap
> Dnd 194 add full width link button

- src/Atoms/List/List.tsx
- src/Atoms/Number/Number.stories.tsx
- src/Atoms/Number/Number.tsx
- src/Atoms/Spinner/Spinner.md
- src/Atoms/Spinner/Spinner.stories.tsx
- src/Atoms/Spinner/Spinner.tsx
- src/Atoms/Spinner/Spinner.types.ts
- src/Atoms/Time/Time.tsx
- src/Molecules/Development/Development.stories.tsx
- src/Molecules/LabeledValue/LabeledValue.stories.tsx
- src/Molecules/ListWithTitles/ListWithTitles.stories.tsx
- src/__snapshots__/storyshots.test.ts.snap
Also ran prettier, which was really needed (🤷‍♂️) but it should be in separate commits.
> fix: unique spinner ids

- src/Molecules/Button/Button.stories.tsx
- src/Molecules/Button/Button.tsx
- src/Molecules/Button/Button.types.ts
- src/Molecules/Link/Link.stories.tsx
- src/Molecules/Link/Link.tsx
- src/Molecules/Link/Link.types.ts
- src/Molecules/LinkBuy/LinkBuy.stories.tsx
- src/Molecules/LinkBuy/LinkBuy.tsx
- src/Molecules/LinkSell/LinkSell.stories.tsx
- src/Molecules/LinkSell/LinkSell.tsx
- src/__snapshots__/storyshots.test.ts.snap
Got feedback from the developers that they need this for SEO
> feat: add rel prop to links

- src/Atoms/Number/Number.tsx
- src/Molecules/Development/__snapshots__/Development.stories.storyshot
> fix(Number): force -0 => 0

- src/Atoms/Typography/Typography.stories.tsx
- src/Atoms/Typography/Typography.tsx
- src/Atoms/Typography/Typography.types.ts
- src/Atoms/Typography/__snapshots__/Typography.stories.storyshot
- src/Molecules/Select/Select.tsx
- src/Molecules/Select/__snapshots__/Select.stories.storyshot
- src/common/utils.test.ts
- src/common/utils.ts
* Chevron was not clickable
* There was an unnecessary span for screen readers announcing what the transparent select already did.
> Select fix

- src/Molecules/Number/Number.stories.tsx
- src/Molecules/Number/Number.tsx
- src/Molecules/Number/__snapshots__/Number.stories.storyshot
So it turned out that react intl does something weird to the '-' sign
> Fix -0 attempt 2

- src/Molecules/Select/Select.tsx
- src/Molecules/Select/__snapshots__/Select.stories.storyshot
> fix: correct select height

- src/Molecules/CollapsibleCard/Collapsible.types.ts
- src/Molecules/CollapsibleCard/CollapsibleCard.stories.tsx
- src/Molecules/CollapsibleCard/CollapsibleCard.tsx
- src/Molecules/CollapsibleCard/__snapshots__/CollapsibleCard.stories.storyshot
- src/Molecules/CollapsibleCard/index.ts
- src/index.ts
I believe @mjmonline is the original author when it lived in closed source, so all credit goes to him.
> Move over collapsible card and fix slowness

- src/Atoms/Table/Tr/Tr.tsx
- src/Atoms/Table/Tr/Tr.types.ts
* feat: made a table row clickable
> Add onClick on table row

- src/Molecules/Button/Button.stories.tsx
- src/Molecules/Button/Button.tsx
- src/Molecules/Button/Button.types.ts
- src/Molecules/Button/__snapshots__/Button.stories.storyshot
@shmidt-i @mjmonline pls take a look and feel free to fix if I've forgotten anything
> Disabled button fix

- src/Molecules/Tabs/Tabs.stories.tsx
- src/Molecules/Tabs/Tabs.tsx
- src/Molecules/Tabs/__snapshots__/Tabs.stories.storyshot
same as https://github.com/nordnet/ui/pull/228 just for tabs
> conditionally render tabs

- src/Atoms/Media/Media.stories.tsx
- src/Atoms/Media/Media.test.tsx
- src/Atoms/Media/__snapshots__/Media.stories.storyshot
This to stop all the warnings about it
> fix: stop using theme.size internally

- src/Molecules/Button/Button.tsx
- src/Molecules/Input/Text/__snapshots__/Text.stories.storyshot
- src/Molecules/Link/Link.tsx
- src/Molecules/PageHeaderCard/__snapshots__/PageHeaderCard.stories.storyshot
- src/common/tracking.ts
- src/common/tracking.types.ts
- src/index.ts
Added tracking context to enable tracking and implemented it in button and link
> enable tracking in buttons and links

- src/Molecules/Link/Link.tsx
- src/common/tracking.types.ts
fix link not rendering if tracking context not available
> Fix link exception when tracking unavailable

- src/Molecules/Link/Link.tsx
- src/Molecules/Link/__snapshots__/Link.stories.storyshot
> fix: reset background of button in link component

- src/Molecules/Modal/Modal.tsx
- src/Molecules/Modal/ModalInner.tsx
- src/Molecules/Modal/__snapshots__/Modal.stories.storyshot
Expose modal Content to be able to style it, only set max-height in desktop.
> Feat: expose modal content

- src/Molecules/FormField/FormField.tsx
- src/Molecules/Input/Text/__snapshots__/Text.stories.storyshot
> fix: hideLabel Input.Text

- src/Atoms/Icon/__snapshots__/Icon.stories.storyshot
- src/Atoms/Icon/components/Circle.tsx
- src/Atoms/Icon/index.ts
> fix: add solid circle to icons

- src/Molecules/Button/Button.tsx
- src/Molecules/Input/Select/__snapshots__/Select.stories.storyshot
- src/Molecules/Input/Text/__snapshots__/Text.stories.storyshot
- src/Molecules/Link/Link.tsx
- src/Molecules/PageHeaderCard/__snapshots__/PageHeaderCard.stories.storyshot
- src/common/tracking.ts
- src/common/tracking.types.ts
- src/index.ts
Add tracking context and apply it to link and button components
> Feat: add tracking context

- src/Molecules/Input/Number/Number.stories.tsx
- src/Molecules/Input/Number/Number.tsx
- src/Molecules/Input/Number/Number.types.ts
- src/Molecules/Input/Number/__snapshots__/Number.stories.storyshot
> Feat: addons for input number

- src/Molecules/Input/Select/wrappers.tsx
since `Input.Number` has z-index as 3
> fix  z-index

- src/Molecules/Input/Text/Text.tsx
- src/Molecules/Input/Text/__snapshots__/Text.stories.storyshot
> fix: size prop

- src/Molecules/Modal/Modal.stories.tsx
- src/Molecules/Modal/Modal.types.ts
- src/Molecules/Modal/ModalInner.tsx
- src/Molecules/Modal/__snapshots__/Modal.stories.storyshot
Adds a new optional prop `footer` to `Modal`.
> Add optional footer to Modal

- src/Molecules/FormField/FormField.stories.tsx
- src/Molecules/FormField/FormField.tsx
- src/Molecules/FormField/FormField.types.ts
- src/Molecules/FormField/__snapshots__/FormField.stories.storyshot
- src/Molecules/Input/Checkbox/__snapshots__/Checkbox.stories.storyshot
- src/Molecules/Input/Number/Number.stories.tsx
- src/Molecules/Input/Number/Number.tsx
- src/Molecules/Input/Number/Number.types.ts
- src/Molecules/Input/Number/__snapshots__/Number.stories.storyshot
- src/Molecules/Input/Radio/__snapshots__/Radio.stories.storyshot
- src/Molecules/Input/Select/__snapshots__/Select.stories.storyshot
- src/Molecules/Input/Text/Text.stories.tsx
- src/Molecules/Input/Text/Text.tsx
- src/Molecules/Input/Text/Text.types.ts
- src/Molecules/Input/Text/__snapshots__/Text.stories.storyshot
- src/Molecules/Input/Textarea/Textarea.stories.tsx
- src/Molecules/Input/Textarea/Textarea.tsx
- src/Molecules/Input/Textarea/Textarea.types.ts
- src/Molecules/Input/Textarea/__snapshots__/Textarea.stories.storyshot
> feat: add support to pass addon to label

- package.json
- src/Atoms/Skeleton/Skeleton.stories.tsx
- src/Atoms/Skeleton/Skeleton.tsx
- src/Atoms/Skeleton/Skeleton.types.ts
- src/Atoms/Skeleton/__snapshots__/Skeleton.stories.storyshot
- src/Atoms/Skeleton/index.ts
- src/Atoms/Typography/__snapshots__/Typography.stories.storyshot
- src/Molecules/Number/__snapshots__/Number.stories.storyshot
- src/Organisms/Development/__snapshots__/Development.stories.storyshot
- src/index.ts
- src/theme/__snapshots__/Theme.stories.storyshot
- src/theme/theme.ts
- src/theme/theme.types.ts
Adding everyone because Ivan is on 🏖
> feat: skeleton component

- src/Molecules/Modal/Modal.stories.tsx
- src/Molecules/Modal/Modal.tsx
- src/Molecules/Modal/ModalInner.tsx
- src/Molecules/Modal/__snapshots__/Modal.stories.storyshot
* Remove internal scrollbar
* Set max-height higher up in the tree
* Add className prop to `Dialog` directly which means style changes to the `Dialog` element can now be done by just doing `const StyledModal = styled(Modal)`
> Fix: Modal remove internal scrollbar handling

- src/Molecules/Input/Text/Text.stories.tsx
- src/Molecules/Input/Text/Text.tsx
- src/Molecules/Input/Text/Text.types.ts
- src/Molecules/Input/Text/__snapshots__/Text.stories.storyshot
This PR exposes the `type` prop on `Input.Text` (to be able to set `email`, `password` etc).
> Input types

- src/Atoms/Icon/__snapshots__/Icon.stories.storyshot
- src/Atoms/Icon/components/BrowserWindow.tsx
- src/Atoms/Icon/index.ts
> Browser icon

- src/Molecules/Modal/ModalInner.tsx
- src/Molecules/Modal/__snapshots__/Modal.stories.storyshot
Don't want to render a header if no title and hideClose is true
> fix(modal): fix logic to hide header

- src/Atoms/CssGrid/CssGrid.stories.tsx
- src/Atoms/CssGrid/CssGrid.tsx
- src/Atoms/CssGrid/__snapshots__/CssGrid.stories.storyshot
* align-self -> -ms-grid-row-align
* justify-self -> -ms-grid-column-align
* place-self -> both (if neccesary)
> fix: 🐛 add -ms grid styles for align justify place self

- src/Molecules/CardWithTitle/CardWithTitle.stories.tsx
- src/Molecules/CardWithTitle/CardWithTitle.tsx
- src/Molecules/CardWithTitle/__snapshots__/CardWithTitle.stories.storyshot
- src/Organisms/CardWithTabs/CardWithTabs.tsx
- src/Organisms/CardWithTabs/__snapshots__/CardWithTabs.stories.storyshot
> Revert "Feat/update card with title"

- package.json
- yarn.lock
got a warning about a package vulnerability, decided to bump react dependencies while at it.
> fix: resolution to transitive dependency, also bump react and react-dom

- src/Atoms/Icon/__snapshots__/Icon.stories.storyshot
- src/Atoms/Icon/components/Apartment.tsx
- src/Atoms/Icon/components/House.tsx
- src/Atoms/Icon/components/Increase.tsx
- src/Atoms/Icon/components/Move.tsx
- src/Atoms/Icon/index.ts
Added new icons for the mortgage page flow.
> New Icons for Mortgage Flow

- src/Atoms/Pill/Pill.tsx
- src/Atoms/Pill/__snapshots__/Pill.stories.storyshot
hate this warning, had to get rid of it
> fix: omit barColor too

- src/Molecules/CardWithTitle/CardWithTitle.stories.tsx
- src/Molecules/CardWithTitle/CardWithTitle.tsx
- src/Molecules/CardWithTitle/CardWithTitle.types.ts
- src/Molecules/CardWithTitle/__snapshots__/CardWithTitle.stories.storyshot
- src/Organisms/CardWithTabs/CardWithTabs.stories.tsx
- src/Organisms/CardWithTabs/__snapshots__/CardWithTabs.stories.storyshot
Added variant to props for cards to use extra padding and a larger heading on CardWithTabs and CardWithTitles.
The design document calls this version Big.
> Add big card version

- src/Atoms/FadedScroll/FadedScroll.styles.tsx
- src/Atoms/FadedScroll/__snapshots__/FadedScroll.stories.storyshot
- src/Molecules/CardWithTitle/__snapshots__/CardWithTitle.stories.storyshot
- src/Molecules/Drawer/__snapshots__/Drawer.stories.storyshot
- src/Molecules/Input/Select/lib/MultiSelectList/__snapshots__/MultiSelectList.stories.storyshot
- src/Molecules/Input/Select/lib/SingleSelectList/__snapshots__/SingleSelectList.stories.storyshot
- src/Molecules/Modal/__snapshots__/Modal.stories.storyshot
- src/Organisms/CardWithTabs/__snapshots__/CardWithTabs.stories.storyshot
@edenvin is going to take over this.
> fix: fadedscroll ie11 fix

- src/Molecules/Timeline/Timeline.stories.tsx
new Date() does not work with testing, hardcoding a specific date
> test: 💍 fixed broken timeline test with new date

- .npmignore
This will cut the unpacked-size by 8 times.
> fix: not packing storyshots in package

- src/Molecules/FlexTable/FlexTable.stories.tsx
- src/Molecules/FlexTable/FlexTable.tsx
- src/Molecules/FlexTable/Row/Row.tsx
- src/Molecules/FlexTable/shared/FlexTableProvider/FlexTableProvider.tsx
- src/Molecules/FlexTable/shared/FlexTableProvider/FlexTableProvider.types.ts
Makes distance between columns assignable and if desired Media responsive
> feat: 🎸 column distance for flex table

- src/Molecules/FlexTable/Cell/Cell.types.ts
- src/Molecules/FlexTable/Cell/TextWrapper.tsx
- src/Molecules/FlexTable/FlexTable.stories.tsx
- src/Molecules/FlexTable/Footer/Footer.types.ts
- src/Molecules/FlexTable/Footer/TextWrapper.tsx
- src/Molecules/FlexTable/Header/HeaderContent/HeaderContent.types.ts
- src/Molecules/FlexTable/Header/HeaderContent/TextWrapper.tsx
This allows the user to have a custom cell, header that has some parts truncated and other parts not while keeping the font and fontsize correct
> feat: 🎸 allow disable of truncation on table text wrappers

- src/Atoms/Icon/__snapshots__/Icon.stories.storyshot
- src/Atoms/Icon/components/PlusThin.tsx
- src/Atoms/Icon/index.ts
> feat: 🎸 thinner plus icon added

- src/Atoms/CssGrid/CssGrid.stories.tsx
- src/Atoms/CssGrid/CssGrid.tsx
- src/Atoms/CssGrid/__snapshots__/CssGrid.stories.storyshot
Now possible to override with zero gutter for different screen sizes. Also add story to show the functionality.
> fix: add possibility to override with zero gutter

- src/Molecules/InfoBar/__snapshots__/InfoBar.stories.storyshot
- src/Molecules/PageHeaderCard/__snapshots__/PageHeaderCard.stories.storyshot
- src/Molecules/PageWrapper/PageWrapper.tsx
- src/Molecules/PageWrapper/__snapshots__/PageWrapper.stories.storyshot
To help with making the print experience of acc overview  a little nicer (I know...), this one helps :)
> fix(PageWrapper): no max-width when printing

- src/Molecules/Modal/Modal.stories.tsx
- src/Molecules/Modal/Modal.types.ts
- src/Molecules/Modal/ModalInner.tsx
- src/Molecules/Modal/__snapshots__/Modal.stories.storyshot
To more easily be able to achieve [this](https://nordnet.invisionapp.com/d/main?origin=v7#/console/20177685/428042572/preview?scrollOffset=2567.77783203125).
> Add full screen prop modal

- src/Molecules/ProgressBar/ProgressBar.stories.tsx
- src/Molecules/ProgressBar/ProgressBar.tsx
- src/Molecules/ProgressBar/ProgressBar.types.ts
- src/Molecules/ProgressBar/__snapshots__/ProgressBar.stories.storyshot
- src/theme/__snapshots__/Theme.stories.storyshot
- src/theme/theme.ts
- src/theme/theme.types.ts
> fix(ProgressBar): active step can be failed

- src/Molecules/Modal/Modal.stories.tsx
- src/Molecules/Modal/Modal.tsx
- src/Molecules/Modal/Modal.types.ts
- src/Molecules/Modal/ModalInner.tsx
- src/Molecules/Modal/__snapshots__/Modal.stories.storyshot
- Adjust mobile widths on different screen sizes
- Adjust padding on mobile
> fix/adjust modal widths, padding on mobile

- src/Molecules/Input/Text/Text.tsx
- src/Molecules/Input/Text/__snapshots__/Text.stories.storyshot
> fix: 🐛 safari input type search bug

- src/Atoms/Icon/Icon.stories.tsx
- src/Atoms/Icon/__snapshots__/Icon.stories.storyshot
- src/Atoms/Icon/components/Chevron.tsx
- src/Atoms/Icon/index.ts
> feat: add chevron icon with direction props

- src/Molecules/DatePicker/DatePicker.tsx
authors: Fredrik Lütz & William Bruce
> fix: 🐛 date picker range click handling

- src/Molecules/DatePicker/DatePicker.tsx
authors: william bruce & fredrik lütz
> fix: 🐛 support selecting a single date with range picker

- src/Molecules/DatePicker/DatePicker.tsx
Authors: William Bruce, Fredrik Lütz
> fix: 🐛 swap month if date is clicked outside of current month

- src/Molecules/DatePicker/DatePicker.tsx
Authors: William Bruce, Fredrik Lütz
> fix: 🐛 date picker disabled dates via text input

- src/Molecules/DatePicker/Calendar/Calendar.tsx
- src/Molecules/DatePicker/Calendar/Calendar.types.ts
- src/Molecules/DatePicker/DatePicker.tsx
- src/Molecules/DatePicker/shared/dateUtils.ts
Authors: William Bruce, Marcus Hogler, Fredrik Lütz
> feat: 🎸 step to next/prev month with arrow keys

- src/Molecules/SelectionCard/SelectionCard.tsx
- src/Organisms/StatusModal/StatusModal.tsx
Fill to color for icons in SelectionCard and StatusModal
> fix: add fill instead of color for icons

- src/Atoms/Icon/__snapshots__/Icon.stories.storyshot
- src/Atoms/Icon/components/SellingpointPhone.tsx
- src/Atoms/Icon/index.ts
add new phone sellingpoint icon
> fix: 🐛 Icon

- src/Molecules/DatePicker/Double/DoubleDatePicker.tsx
- src/Molecules/DatePicker/Double/__snapshots__/DoubleDatePicker.stories.storyshot
- src/Molecules/DatePicker/__snapshots__/DatePicker.stories.storyshot
> fix: make double date picker wrap better

- src/Molecules/Pagination/Pagination.tsx
- src/Molecules/Pagination/Pagination.types.ts
- src/Molecules/Pagination/__snapshots__/Compact.stories.storyshot
- src/Molecules/Pagination/__snapshots__/Large.stories.storyshot
- src/Molecules/Pagination/__snapshots__/Regular.stories.storyshot
- src/Molecules/Pagination/variants/Compact.tsx
- src/Molecules/Pagination/variants/Large.tsx
- src/Molecules/Pagination/variants/Regular.tsx
We want to hide prev page button if on page1 and hide next page button if on last page
> Hide page buttons

- src/Molecules/FeedbackBanner/FeedbackBanner.stories.tsx
- src/Molecules/FeedbackBanner/FeedbackBanner.tsx
- src/Molecules/FeedbackBanner/FeedbackBanner.types.ts
- src/Molecules/FeedbackBanner/__snapshots__/FeedbackBanner.stories.storyshot
dictates the background color of the banner, used depending of scope
placement
> feat: 🎸 add scope prop to FeedbackBanner

- package.json
- src/Molecules/Input/Select/Select.stories.tsx
- src/Molecules/Input/Select/machine.ts
- yarn.lock
Warning was introduced in this release https://github.com/davidkpiano/xstate/releases/tag/xstate%404.11.0
> fix(Input.Select): fix the xstate machine warning after main app was updated to the semilatest xstate

- src/Molecules/Button/Button.types.ts
We needed a reference to the form we're submitting since the actual submit button is rendered through a portal in order side panel. If this is acceptable then we are fine :)
> add form prop on button

- src/Atoms/CssGrid/CssGrid.stories.tsx
- src/Molecules/InfoBar/InfoBar.stories.tsx
- src/Molecules/Input/Phone/Phone.stories.tsx
- src/Molecules/Input/Phone/Phone.styled.ts
- src/Molecules/Input/Phone/Phone.tsx
- src/Molecules/Input/Phone/__snapshots__/Phone.stories.storyshot
- src/Molecules/Timeline/Timeline.stories.tsx
Adds so you can choose between `small` or `normal` in `PhoneInput`.
> fix: 🐛 adds size prop to phone input

- src/Molecules/Input/Phone/Phone.tsx
- src/Molecules/Input/Phone/__snapshots__/Phone.stories.storyshot
> fix: 🐛 adjust finnish country code for phone input

- src/Molecules/Input/Select/Select.stories.tsx
- src/Molecules/Input/Select/__snapshots__/Select.stories.storyshot
- src/Molecules/Input/Select/lib/OptionGroup/OptionGroup.tsx
- src/Molecules/Input/Select/lib/OptionGroup/index.ts
- src/Molecules/Input/Select/lib/SingleSelectList/SingleSelectList.tsx
- src/Molecules/Input/Select/lib/defaults/ListItem.tsx
- src/Molecules/Input/Select/lib/defaults/ListItemMultiple.tsx
- src/Molecules/Input/Select/machine.ts
Co-authored-by: Tobias Lundell <lundell.tobias@gmail.com>
Co-authored-by: Oscar Sandberg <oscar.sandberg@nordnet.se>
Co-authored-by: Marcus Hogler <marcus.hogler@nordnet.se>
> feat(input-select): add multi select with grouping

- src/Molecules/Input/Select/Select.stories.tsx
- src/Molecules/Input/Select/Select.tsx
- src/Molecules/Input/Select/Select.types.ts
- src/Molecules/Input/Select/__snapshots__/Select.stories.storyshot
- src/Molecules/Input/Select/lib/MultiSelectList/MultiSelectList.tsx
- src/Molecules/Input/Select/lib/MultiSelectList/__snapshots__/MultiSelectList.stories.storyshot
- src/Molecules/Input/Select/lib/SingleSelectList/SingleSelectList.tsx
- src/Molecules/Input/Select/lib/SingleSelectList/__snapshots__/SingleSelectList.stories.storyshot
- src/Molecules/Input/Select/lib/defaults/ListFullScreen.tsx
- src/Molecules/Input/Select/lib/defaults/ListItem.tsx
- src/Molecules/Input/Select/lib/defaults/ListItemMultiple.tsx
- src/Molecules/Input/Select/lib/defaults/Search.tsx
- src/Molecules/Input/Select/lib/defaults/index.ts
- src/Molecules/Input/Select/lib/wrappers/List.tsx
- src/Molecules/Input/Select/lib/wrappers/ListItem.tsx
- src/Molecules/Input/Select/lib/wrappers/Search.tsx
- src/Molecules/Input/Select/machine.ts
- src/Molecules/PersistentTooltip/__snapshots__/PersistentTooltip.stories.storyshot
- src/Molecules/Tooltip/__snapshots__/Tooltip.stories.storyshot
Co-authored-by: David Skog <david.skog@nordnet.se>
Co-authored-by: LifeOfMichal <dzienis.michal.maciej@gmail.com>
> feat: support of fullScreen in mobile for select element

- src/Molecules/Input/Select/lib/hooks.ts
Delete "jump scroll to" behaviour when clicking Input.Selects on larger screen sizes. https://jira.prod.nordnet.se/browse/DISCO-5694
> Disco 5694

- src/Molecules/Pagination/Compact.stories.tsx
- src/Molecules/Pagination/Large.stories.tsx
- src/Molecules/Pagination/PageItems.tsx
- src/Molecules/Pagination/Pagination.tsx
- src/Molecules/Pagination/Pagination.types.ts
- src/Molecules/Pagination/PaginationRouteHelper.tsx
- src/Molecules/Pagination/Regular.stories.tsx
- src/Molecules/Pagination/__snapshots__/Compact.stories.storyshot
- src/Molecules/Pagination/__snapshots__/Large.stories.storyshot
- src/Molecules/Pagination/__snapshots__/Regular.stories.storyshot
- src/Molecules/Pagination/variants/Compact.tsx
- src/Molecules/Pagination/variants/CompactLinks.tsx
- src/Molecules/Pagination/variants/Large.tsx
- src/Molecules/Pagination/variants/LargeLinks.tsx
- src/Molecules/Pagination/variants/Regular.tsx
- src/Molecules/Pagination/variants/RegularLinks.tsx
- src/Molecules/Pagination/variants/components/ChevronIcon.tsx
- src/Molecules/Pagination/variants/components/CompactComponents.tsx
- src/Molecules/Pagination/variants/components/LargeComponents.tsx
- src/Molecules/Pagination/variants/components/RegularComponents.tsx
- src/theme/createDarkColors.tsx
- src/theme/createLightColors.tsx
- src/theme/theme.types.ts
render pagination links instead of buttons if getPageHref is supplied
> feat: 🎸 add link-based pagination variants

- src/Molecules/Input/Radio/__snapshots__/Radio.stories.storyshot
Authors: William Bruce, Marcus Hogler
> fix: 🐛 update input radio snapshot

- CHANGELOG.md
Co-authored-by: Anton Bergwall, Marcus Hogler
> docs: ✏️ clean up changelog with breaking changes for badge

- src/Molecules/Badge/components/NumberBadge/NumberBadge.constants.ts
- src/Molecules/Badge/components/NumberBadge/NumberBadge.stories.tsx
- src/Molecules/Badge/components/NumberBadge/NumberBadge.types.ts
- src/Molecules/Badge/components/NumberBadge/__snapshots__/NumberBadge.stories.storyshot
> fix: add xs size number badge

- src/Molecules/Switch/Switch.stories.tsx
- src/Molecules/Switch/Switch.types.ts
- src/Molecules/Switch/SwitchToggle.tsx
- src/Molecules/Switch/__snapshots__/Switch.stories.storyshot
Design and contract adjustments for the SwitchToggle
> fix: 🐛 adjusted styling and size of the SwitchToggle

- src/Molecules/Input/Number/Number.stories.tsx
- src/Molecules/Input/Number/Number.tsx
- src/Molecules/Input/Number/__snapshots__/Number.stories.storyshot
- src/Molecules/Input/Text/Text.stories.tsx
- src/Molecules/Input/Text/Text.tsx
- src/Molecules/Input/Text/__snapshots__/Text.stories.storyshot
Fix issue with Input.Text & Input.Numeric quite variant is having issue
when you focus on element it was flicker if you have right/left addon
> fix: 🐛 remove padding to fix flicker in Variant="quiet"

- src/Molecules/FeedbackBanner/FeedbackBanner.stories.tsx
- src/Molecules/FeedbackBanner/FeedbackBanner.tsx
- src/Molecules/FeedbackBanner/FeedbackBanner.types.ts
- src/Molecules/FeedbackBanner/__snapshots__/FeedbackBanner.stories.storyshot
defaults to true, set to false to remove icon
> feat: 🎸 add withIcon prop to FeedbackBanner

- src/theme/createDarkColors.tsx
- src/theme/createLightColors.tsx
- src/theme/theme.types.ts
> feat(theme): add dropdown button colors

- src/Molecules/AccordionItem/AccordionItem.stories.tsx
- src/Molecules/AccordionItem/AccordionItem.tsx
- src/Molecules/AccordionItem/AccordionItem.types.ts
- src/Molecules/AccordionItem/__snapshots__/AccordionItem.stories.storyshot
pass a react node to be a right addon for accordion items expand button
> feat: 🎸 add right addon prop to accordion item

- src/Atoms/Pill/Pill.mdx
- src/Atoms/Pill/Pill.stories.tsx
- src/Atoms/Pill/__snapshots__/Pill.stories.storyshot
- src/Atoms/Pill/components/RoundedPill/RoundedPill.tsx
- src/Atoms/Pill/components/RoundedPill/RoundedPill.types.ts
Add optional development to Rounded Pill.
> feat: 🎸 add optional development to Rounded Pill

- src/Molecules/Fieldset/__snapshots__/Fieldset.stories.storyshot
- src/Molecules/Input/Checkbox/Checkbox.shape.ts
- src/Molecules/Input/Checkbox/Checkbox.stories.tsx
- src/Molecules/Input/Checkbox/Checkbox.tsx
- src/Molecules/Input/Checkbox/Checkbox.types.ts
- src/Molecules/Input/Checkbox/__snapshots__/Checkbox.stories.storyshot
- src/Molecules/Input/Select/lib/MultiSelectList/__snapshots__/MultiSelectList.stories.storyshot
Adds round option to input checkbox, TP-18383
> feat: 🎸 Round checkbox

- src/Atoms/Flexbox/Flexbox.stories.tsx
- src/Atoms/Flexbox/Flexbox.tsx
- src/Atoms/Flexbox/Flexbox.types.ts
- src/Atoms/Flexbox/__snapshots__/Flexbox.stories.storyshot
Css gap property is short hand for 'row-gap' and 'column-gap' and can be used to
set spacing between rows and columns inside a flex container. The added
property takes in either a number, string, or an object {column:
number, row: number} so that we can set either units or custom css units
(px, %, vw etc.)
I guess this property could, eventually, deprecate the "gutter" property over time.
> feat: 🎸 add gap property to <Flexbox /> component

- src/Molecules/PromotionBanner/PromotionBanner.tsx
- src/Molecules/PromotionBanner/PromotionBanner.types.ts
PromotionBannerProps removing unused type, using useCallback for
performance purposes
> fix: 🐛 using useCallback and removing unused type for Promotion banner

- src/Atoms/Icon/__snapshots__/Icon.stories.storyshot
- src/Atoms/Icon/action/__snapshots__/Action.stories.storyshot
- src/Atoms/Icon/action/arrowNegative/ArrowNegative16.tsx
- src/Atoms/Icon/action/arrowNegative/ArrowNegative24.tsx
- src/Atoms/Icon/action/arrowNegative/index.ts
- src/Atoms/Icon/action/arrowPositive/ArrowPositive16.tsx
- src/Atoms/Icon/action/arrowPositive/ArrowPositive24.tsx
- src/Atoms/Icon/action/arrowPositive/index.ts
- src/Atoms/Icon/action/arrowRight/ArrowRight24.tsx
- src/Atoms/Icon/action/arrowRight/index.ts
- src/Atoms/Icon/action/index.ts
- src/Molecules/Badge/Badge.md
- ArrowRight24
- ArrowPositive16
- ArrowPositive24
- ArrowNegative16
- ArrowNegative24
> feat: add icons

- src/theme/createDarkColors.tsx
- src/theme/createLightColors.tsx
- src/theme/theme.types.ts
Light mode to use only Teal 500 and Dark mode Teal 400 for allocation bar
> feat: 🎸 add allocation bar colour

- src/Molecules/PromotionBanner/PromotionBanner.tsx
- src/theme/createDarkColors.tsx
update color and add box shadow to promotion banner
> style: 💄 update color and add box shadow to promotion banner

- src/theme/createDarkColors.tsx
- src/theme/createLightColors.tsx
- src/theme/theme.types.ts
> feat: 🎸 add bullet color

- src/theme/createDarkColors.tsx
- src/theme/createLightColors.tsx
- src/theme/theme.types.ts
add color for empty state card text
> feat: 🎸 add color for empty state card tex

- src/Molecules/ProgressIndicator/ProgressIndicator.stories.tsx
- src/Molecules/ProgressIndicator/ProgressIndicator.tsx
- src/Molecules/ProgressIndicator/__snapshots__/ProgressIndicator.stories.storyshot
fix padding for progress indicator and update stories for custom infocallback mobile view
> feat: 🎸 fix padding for progress indicator

- src/Molecules/DistributionBar/DistributionBar.stories.tsx
- src/Molecules/DistributionBar/DistributionBar.styled.ts
- src/Molecules/DistributionBar/DistributionBar.tsx
- src/Molecules/DistributionBar/DistributionBar.types.ts
Center text, fix truncation, align icons, changed contract, changed font size & use case stories.
> fix: 🐛 Updated according to design

- src/theme/createDarkColors.tsx
- src/theme/createLightColors.tsx
- src/theme/theme.types.ts
> feat: 🎸 add new colors

- src/theme/createDarkColors.tsx
- src/theme/createLightColors.tsx
- src/theme/theme.types.ts
add new semantic color for new ListSelectionCard component
> feat: 🎸 add new semantic color

- src/theme/createDarkColors.tsx
- src/theme/createLightColors.tsx
- src/theme/theme.types.ts
> fix: sv-3365 add new link state colors

- src/theme/createDarkColors.tsx
- src/theme/createLightColors.tsx
- src/theme/theme.types.ts
add new new background and text colors for labels
> fix: 🐛 add new colors for label

- src/Atoms/Icon/communication/group/Group16.tsx
- src/Atoms/Icon/communication/group/index.ts
- src/Atoms/Icon/communication/index.ts
> feat: 🎸 add new group icon

- src/Molecules/ProgressIndicator/ProgressIndicator.tsx
change title type according to design
> refactor: 💡 change title type

- src/Molecules/ProgressIndicator/ProgressIndicator.styled.ts
- src/Molecules/ProgressIndicator/ProgressIndicator.tsx
- src/Molecules/ProgressIndicator/ProgressIndicator.types.ts
> feat: 🎸 update the progress indicator component

- src/Atoms/Icon/action/download/Download16.tsx
- src/Atoms/Icon/action/download/index.ts
- src/Atoms/Icon/action/index.ts
> feat: 🎸 Add Download icon

- src/Molecules/FeedbackBanner/FeedbackBanner.tsx
> feat: 🎸 add 4px border-radius

- src/Molecules/Input/Checkbox/Checkbox.tsx
add 2px border radius to Checkbox
> UC-38: Add 2px border-radius to Checkbox

- src/Molecules/DatePicker/Double/DoubleDatePicker.tsx
- src/Molecules/DatePicker/Range/DateRangePicker.tsx
- src/Molecules/DatePicker/Single/DatePicker.tsx
Add 8px border-radius to dropdown for date picker
> feat: 🎸 Add 8px border radius to dropdown for date picker

- src/Molecules/Input/Number/Number.tsx
- src/Molecules/Input/Phone/Phone.styled.ts
- src/Molecules/Input/Text/Text.tsx
- src/Molecules/Input/Textarea/Textarea.tsx
add 4 px border radius to Inputs - Text, Number, Phone and Textarea
> UC-40: add 4px rounded corners to Inputs

- src/Molecules/ProgressIndicator/ProgressIndicator.styled.ts
- src/Molecules/ProgressIndicator/ProgressIndicator.tsx
add 8px border radius to Progress Indicator if not mobile
> feat: 🎸 add 8px border radius to progress indicator

- src/Molecules/AllocationBar/AllocationBar.tsx
- src/Molecules/AllocationBar/AllocationBar.types.ts
Add rounded corners to AllocationBar
> feat: 🎸 rounded corners to AllocationBar

- src/Atoms/Skeleton/Skeleton.tsx
add 8px border radius to skeleton variant text and rect
> feat: 🎸 add 8px border radius to Skeleton

- src/common/PopOver/TooltipContent/TooltipContent.tsx
add 4 px border radius to tooltip and 20 px border radius on top corners if bottom sheet on mobile
> feat: 🎸 add border radius to Tooltip

- src/Molecules/CoachMarks/Bubble/Bubble.tsx
- src/Molecules/CoachMarks/BubbleArrow/BubbleArrow.tsx
- src/Molecules/CoachMarks/BubbleArrow/BubbleArrow.types.ts
- src/Molecules/CoachMarks/CoachMarks.tsx
And remove grey border around CoachMark when it has colored bar variant after talking with design.
> UC-42: Coach Marks rounded corners

- src/Molecules/MultiStepProgress/TopLevel/TopLevel.tsx
add 8px border left to card to align with the border radius
> UC-46: Vertical Progress Card rounded corners and wider blue border

- src/Atoms/Card/Card.tsx
- src/Atoms/DropdownBubble/DropdownBubble.tsx
- src/Atoms/Skeleton/Skeleton.tsx
- src/Molecules/ActionModal/ActionModal.tsx
- src/Molecules/AllocationBar/AllocationBar.tsx
- src/Molecules/Badge/components/LabelBadge/LabelBadge.tsx
- src/Molecules/BarScale/BarScale.tsx
- src/Molecules/Button/components/BaseButton/Button.tsx
- src/Molecules/CoachMarks/Bubble/Bubble.tsx
- src/Molecules/FeedbackBanner/FeedbackBanner.tsx
- src/Molecules/Input/Checkbox/Checkbox.tsx
- src/Molecules/Input/Number/Number.tsx
- src/Molecules/Input/Phone/Phone.styled.ts
- src/Molecules/Input/Select/lib/wrappers/FormFieldOrFragment.tsx
- src/Molecules/Input/Text/Text.tsx
- src/Molecules/Input/Textarea/Textarea.tsx
- src/Molecules/LineScale/LineScale.tsx
- src/Molecules/Modal/ModalInner.tsx
- src/Molecules/MultiStepProgress/TopLevel/TopLevel.tsx
- src/Molecules/Pagination/variants/components/LargeComponents.tsx
- src/Molecules/ProgressIndicator/ProgressIndicator.styled.ts
- src/Molecules/PromotionBanner/PromotionBanner.tsx
- src/common/PopOver/TooltipContent/TooltipContent.tsx
- src/theme/theme.ts
- src/theme/theme.types.ts
use set functions for border-radius to prevent snowflaking
> fix: 🐛 use set functions for border-radius

- src/Atoms/Icon/action/check/Check12.tsx
- src/Atoms/Icon/action/check/index.ts
- src/Atoms/Icon/action/copy/Copy12.tsx
- src/Atoms/Icon/action/copy/index.ts
> feat: 🎸 Add new check and copy icons

- src/Atoms/Card/Card.tsx
- src/Molecules/CardWithTitle/CardWithTitle.stories.tsx
✅ Closes: TP-20407
Co-author: @edvber
> fix: 🐛 Pass HTML props to CardWithTitle

- src/Molecules/BarScale/BarScale.tsx
- src/Molecules/BarScale/BarScale.types.ts
- src/Molecules/FlexTable/Row/FooterRow.tsx
- src/Molecules/FlexTable/Row/components/ExpandItems/ExpandItems.tsx
- src/Molecules/LineScale/LineScale.tsx
- src/Molecules/LineScale/LineScale.types.ts
- src/Molecules/Modal/Modal.types.ts
- src/Molecules/Modal/ModalInner.tsx
- src/Molecules/SelectionCard/SelectionCard.tsx
- src/Molecules/Timeline/Timeline.tsx
Needed for a [migration to Styled-components v6](https://styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v6)
> fix: use transient props ($propName) instead of shouldforwardprop

- src/Molecules/Input/Checkbox/Checkbox.stories.tsx
- src/Molecules/Input/Number/Number.stories.tsx
- src/Molecules/Input/Phone/Phone.stories.tsx
- src/Molecules/Input/Select/Select.stories.tsx
- src/Molecules/Input/Text/Text.stories.tsx
- src/Molecules/Input/Text/Text.types.ts
- src/Molecules/Input/Textarea/Textarea.stories.tsx
Additionally, stories were added for every applicable input component
> fix: labelTooltipInModal for all input components

- src/Molecules/MultiStepProgress/TopLevel/TopLevel.tsx
should have rounded corners in breakpoint s also.
> fix: 🐛 rounded corners in breakpoint small

- src/Atoms/Box/Box.types.ts
- src/Molecules/DistributionBar/DistributionBar.stories.tsx
- src/Molecules/DistributionBar/DistributionBar.styled.ts
- src/Molecules/DistributionBar/DistributionBar.tsx
- src/Molecules/DistributionBar/DistributionBar.types.ts
Adding IconPadding and removing unnecessary imageProp prop `DistributionBar`
> feat: 🎸 Adding IconPadding to DistributionBar component

- src/Molecules/Toggle/Toggle.tsx
Toggle component will have a cursor on hover unless it is disabled.
> feat: 🎸 show cursor on hover

- src/Molecules/CoachMarks/CoachMarks.tsx
focuslock was causing the coachmarks to prevent text input in for ex the searchdrawer it also created wonky behaviour with select-fields.
this PR fixes this.
> fix: removed focuslock and added portal in coachmarks

- src/Molecules/CheckList/DrawerTitle.tsx
- src/Molecules/MultiStepProgress/TopLevel/TopLevel.tsx
- [DISCO-10024](https://jira.prod.nordnet.se/browse/DISCO-10024)
- [DISCO-10866](https://jira.prod.nordnet.se/browse/DISCO-10866)
> fix: 🐛 page guidance card gap and checklist setting icon

- src/Molecules/Modal/Modal.stories.tsx
Forgot to add feat flag to trigger build
> feat: trigger build

- package-lock.json
- package.json
- src/Molecules/BottomSheet/BottomSheet.styles.ts
BREAKING CHANGE: few color tokens removed
> update design tokens

- src/Molecules/Select/Group/Group.tsx
- src/Molecules/Select/HiddenSelect.tsx
- src/Molecules/Select/Option/Option.tsx
- src/Molecules/Select/Select.styles.tsx
- src/Molecules/Select/Select.tsx
- src/Molecules/Select/Select.types.ts
- src/Molecules/Select/Trigger/Trigger.tsx
- src/Molecules/Select/ValueDisplay/ValueDisplay.tsx
- src/Molecules/Select/ValueDisplayMultiSelect/ValueDisplayMultiSelect.tsx
- src/Molecules/Select/__tests__/Select.test.tsx
- take className prop
- spread rest props in reusable components
- pick only used props from MUI
> Fix: add more tests to select and minor improvements

- src/Molecules/FeedbackBanner/FeedbackBanner.tsx
Use color tokens and replace usage of OldIcon
> fix: modernize feedback banner  (UC-37)

- src/Molecules/DistributionBar/DistributionBar.stories.tsx
- src/Molecules/DistributionBar/DistributionBar.styled.ts
- src/Molecules/DistributionBar/DistributionBar.tsx
- src/Molecules/DistributionBar/DistributionBar.types.ts
SV-4159 Add hover effect on distribution bar
> SV-4159 add hover effect

- src/Molecules/ControlsListItem/ControlsListItem.types.ts
- src/Molecules/ControlsListItem/ControlsListItemSwitch.stories.tsx
- src/Molecules/ControlsListItem/ControlsListItemSwitch.tsx
used as follows:
```ts
<ControlsListItem.Switch
size="m"
// rest of props here..
/>
```
> feat: Add optional size prop to ControlsListItemSwitch

- src/Molecules/ToastMessage/ToastMessage.stories.tsx
- src/Molecules/ToastMessage/ToastMessage.styled.ts
- src/Molecules/ToastMessage/ToastMessage.tsx
- src/Molecules/ToastMessage/ToastMessage.types.ts
- src/Molecules/ToastMessage/index.ts
- src/index.ts
https://jira.prod.nordnet.se/browse/DISCO-11350
Toasts inform users of a process that an app has performed or will perform. They appear temporarily, towards the bottom of the screen. They shouldn’t interrupt the user experience, and they don’t require user input to disappear.
Toasts provide brief messages about app processes at the bottom of the screen.
Only one toast may be displayed at a time.
Toasts appear temporarily, and disappear on their own without requiring user to dismiss it.
A toast can contain a single action.
> New toast message component

- src/Molecules/Badge/components/TooltipBadge/TooltipBadge.tsx
> feat:Update tooltip badge colour token in ui kit
