nordnet/ui

src/Atoms/Text/Text.stories.tsx, src/Atoms/Text/Text.types.ts
Adding missing stories for `Text` component. Also grouping and cleaning up stories for `bold` property.
=> fix: add missing stories for text component

src/Atoms/CssGrid/CssGrid.tsx, src/Atoms/CssGrid/__snapshots__/CssGrid.stories.storyshot
When we are trying to do ellipsis on text then the grid was not contained. See examples and solutions here:  https://css-tricks.com/preventing-a-grid-blowout/
=> fix: prevent grid blowout

src/Atoms/Number/Number.stories.tsx, src/Atoms/Number/Number.tsx, src/Atoms/Number/__snapshots__/Number.stories.storyshot, src/Molecules/Development/Development.stories.tsx, src/Molecules/Development/Development.tsx, src/Molecules/Development/__snapshots__/Development.stories.storyshot
Mainly fixes a case where the value sent in (e.g. value=0.1) is non-zero, but the rounded value (e.g. value=0) is zero, so it got a plus sign and development color, even though it shouldn't.
The rest is printing warnings for a very common, bad use case, namely that ticks are snake cased. And I also added some documentation. See the commits which should be chunked up properly.
=> Number and development improvements

src/Atoms/Number/Number.tsx, src/Molecules/Development/__snapshots__/Development.stories.storyshot
I screwed up the rounding if decimals was `0` in my recent PR.
=> fix: rounding with zero decimals

src/Atoms/Flexbox/Flexbox.tsx
It wasn't possible to e.g. apply `shrink={0}` to an flexbox item before because of boolean check.
=> feat: enabled to use items style with 0 as value

src/Molecules/CollapsibleCard/CollapsibleCard.stories.tsx, src/Molecules/CollapsibleCard/CollapsibleCard.tsx, src/Molecules/CollapsibleCard/__snapshots__/CollapsibleCard.stories.storyshot
The `onClick` callback was called both on `touchstart` and `click` events on mobile phones.
=> fix(CollapsibleCard): prevent onClick being called twice on mobiles

src/Atoms/Spinner/Spinner.stories.tsx, src/Atoms/Spinner/Spinner.tsx, src/Atoms/Spinner/Spinner.types.ts, src/Atoms/Spinner/__snapshots__/Spinner.stories.storyshot
A suggestion, we have this on graph component that if the data is loaded fast enough that the user is not even thinking about pressing F5 again yet we don't show the spinner at all.
=> feat(spinner): add delay to show spinner

src/Molecules/Input/Number/Number.tsx, src/Molecules/Input/Number/Number.types.ts, src/Molecules/Input/Number/__snapshots__/Number.stories.storyshot
input type number does not work well with localized values when using it together with react-intl. It's either we remove react-intl from this input or make it as text (as per this PR) with normalizing entered values to be numbers.
[inputmode](https://caniuse.com/#search=inputmode) is used for opening numerical keyboard on mobile devices when one has input type text, it's supported in few latest versions of  chrome and iOS safari which covers most of the users
=> make number input as type text

.storybook/webpack.config.js, src/Molecules/Input/Select/Select.stories.tsx
This PR fixes storysource not showing for any story under `Molecules | Input / Select`, e.g. https://nordnet.github.io/ui/?path=/story/molecules-input-select--default
=> fix: storysource

src/Molecules/Input/Number/Number.tsx, src/Molecules/Input/Number/__snapshots__/Number.stories.storyshot, src/common/NormalizedElements/NormalizedInput.tsx
Made the number left aligned when steppers aren't used. Steppers aren't used when noSteppers is set or when either/both left and right addon is used.
=> feat: 🎸 left align number when no steppers for input.number

src/Molecules/FeedbackBanner/FeedbackBanner.tsx, src/Molecules/FeedbackBanner/__snapshots__/FeedbackBanner.stories.storyshot
=> fix: 🐛 FeedbackBanner text no longer overflows in IE

src/Atoms/Portal/__snapshots__/Portal.stories.storyshot, src/Atoms/Typography/Typography.tsx, src/Molecules/CardWithTitle/__snapshots__/CardWithTitle.stories.storyshot, src/Molecules/CollapsibleCard/__snapshots__/CollapsibleCard.stories.storyshot, src/Molecules/Drawer/__snapshots__/Drawer.stories.storyshot, src/Molecules/Modal/__snapshots__/Modal.stories.storyshot, src/Molecules/Number/__snapshots__/Number.stories.storyshot, src/Molecules/PageHeaderCard/__snapshots__/PageHeaderCard.stories.storyshot, src/Organisms/CardWithTabs/__snapshots__/CardWithTabs.stories.storyshot
Before this fix:
If using `as`-prop in typography the `CleanSpan` is never used and therefore a warning/error is shown in the developer console if any other non-DOM prop is passed to the component.
```
<Typography as="h1" color={t = t.color.primary} />
```
After this fix:
The prop cleaning logic is applied even when using an `as` prop.
=> typography `as` is no longer bypassing the clean-step

src/Molecules/Button/Button.tsx, src/Molecules/Button/Button.types.ts
I'm very unsure about the best way to solve this problem but basically I want to allow some (or preferably all) React button attributes on the UI button component. Allowing all of them does however pose some problems as some conflict with the current Button props.
I've also thought about spreading rest of the props into the sharedProps object instead of picking the three I want but that would require me to omit some other props so idk.
=> feat: 🎸 add some onMouse props to Button component

src/Molecules/Modal/ModalInner.tsx
Fixing breaking modal:
**PREV**
**AFTER**
=> fix: 🐛 Modal overflowing vertically is not breaking

src/Molecules/Input/Number/Number.tsx, src/Molecules/Input/Number/__snapshots__/Number.stories.storyshot
Firefox defaults min-width on flex items to auto which breaks % based widths.
Setting it to zero fixes the problem.
=> fix: add min-width 0 to fix firefox

src/Molecules/Modal/Modal.types.ts, src/Molecules/Modal/ModalInner.tsx, src/Molecules/Modal/__snapshots__/Modal.stories.storyshot
Using useOnClickOutside on the backdrop created performance problems in the modals and did not play very well with the framer-motion library. This fix is more performant and works as intended.
=> fix: 🐛 make closing modal on backdrop click more performant

src/Molecules/FlexTable/Row/ExpandItems/ExpandItem.tsx, src/Molecules/FlexTable/__snapshots__/FlexTable.stories.storyshot
Based on input from design, the max-width for expand item is now changed to 75 units/300px
=> fix: 🐛 expand item width to correct from design

src/Molecules/FlexTable/Row/Row.types.ts, src/Molecules/FlexTable/Row/components/ExpandElement.tsx
Removed old `expand` functionality after `expandable` was moved to table-level
=> fix: 🐛 remove legacy expand and rework types

src/Molecules/MultiStepProgress/MultiStepProgress.stories.tsx, src/Molecules/MultiStepProgress/MultiStepProgress.tsx, src/Molecules/MultiStepProgress/MultiStepProgress.types.ts, src/Molecules/MultiStepProgress/__snapshots__/MultiStepProgress.stories.storyshot
Added an optional prop 'closeDrawerOnStepClick' that activates feature of the mobile drawer menu closing on Step (not SubStep) click.
=> fix: 🐛 drawer menu now closes on step click

package.json, yarn.lock
@babel/core was previously upgraded to latest version in #666 to support new syntax features i.e. optional chaining.
Everything seemed fine locally, however the tests would fail in Travis with `SyntaxError: Unexpected token '.'` (see for example https://travis-ci.com/github/nordnet/ui/builds/182385977)
This PR upgrades some other babel dependencies to the latest versions which solves the issue.
=> chore: 🤖 upgrade version of babel dependencies

src/Atoms/Flexbox/Flexbox.types.ts, src/Molecules/FlexTable/BigFlexTable.stories.tsx, src/Molecules/FlexTable/Cell/Cell.tsx, src/Molecules/FlexTable/Cell/Cell.types.ts, src/Molecules/FlexTable/Cell/ExpandCell.tsx, src/Molecules/FlexTable/DefaultFlexTable.stories.tsx, src/Molecules/FlexTable/ExpandableFlexTable.stories.tsx, src/Molecules/FlexTable/FlexTable.mdx, src/Molecules/FlexTable/FlexTable.stories.tsx, src/Molecules/FlexTable/FlexTableWithDifferentColumns.stories.tsx, src/Molecules/FlexTable/FlexTableWithDifferentHeaders.stories.tsx, src/Molecules/FlexTable/FlexTableWithDifferentSizeProps.stories.tsx, src/Molecules/FlexTable/Footer/Footer.tsx, src/Molecules/FlexTable/Footer/Footer.types.ts, src/Molecules/FlexTable/Header/Header.tsx, src/Molecules/FlexTable/Row/components/ExpandElement.tsx, src/Molecules/FlexTable/__snapshots__/FlexTableWithDifferentSizeProps.stories.storyshot, src/Molecules/FlexTable/shared/ColumnProvider/ColumnProvider.types.ts, src/Molecules/FlexTable/shared/ColumnProvider/useFlexCellProps.ts
This change enables `FlexTable` to be rendered on the server. In order to do this, there were a few changes that needed to be done.
- Cell and Footer now accepts same layout properties as Header making them independent from `columnDispatch`
- The old FlexTable API (specifying layout properties only on Header) has been deprecated, but currently still supported for backwards compatibility
- Log warning if old FlexTable API is used instead of the new way
- Update documentation
=> Enable SSR support for FlexTable

src/Atoms/IsomorphicMedia/IsomorphicMedia.tsx, src/Molecules/FlexTable/Cell/Cell.tsx, src/Molecules/FlexTable/Footer/Footer.tsx, src/Molecules/FlexTable/Header/HeaderContent/HeaderContent.tsx, src/Molecules/FlexTable/Header/HeaderContent/HeaderContent.types.ts, src/Molecules/FlexTable/Header/HeaderContent/SortButton.tsx, src/Molecules/FlexTable/Header/HeaderContent/TextWrapper.tsx, src/Molecules/FlexTable/Row/Row.tsx, src/Molecules/FlexTable/Row/components/ExpandItems/ExpandItem.tsx, src/Molecules/FlexTable/shared/RenderForSizes/RenderForSizes.tsx
The `className` that was attached by `StyledDiv` in `IsomorphicMedia` was never consumed by the `Container` component in `RenderForSizes`. Therefore all the media elements were displayed in SSR. Passing the `className` prop to the container component solved the double rendering issue in SSR.
=> fix: 🐛 make render for sizes container use media styles in ssr

src/Molecules/Input/Checkbox/Checkbox.stories.tsx, src/Molecules/Input/Checkbox/Checkbox.types.ts, src/Molecules/Input/Checkbox/__snapshots__/Checkbox.stories.storyshot
The use case for us are the account type checkboxes in the onboarding:
As it currently works, supplying a label as an element (see `Checkbox.stories.tsx` for an example) gives a type violation:
```js
Type 'Element' is not assignable to type 'string'.
```
=> fix: 🐛 allow elements as checkbox labels

src/Molecules/FlexTable/ExpandableFlexTable.stories.tsx
To test this, toggling expand/collapse on controlled examples keep their values.
=> fix: no recalculation on expand for controlled table examples

.storybook/main.js
Change the order of the addons that load our "tool-tabs" (i don't know the correct name of these).
I think it is more important to see the source code of the story first instead of the a11y inspection panel (also, running said inspection is quite heavy for SB which means larger stories might take longer to load if we instantly go to the a11y pane).
=> fix: 🐛 update addon tab order

src/Atoms/Box/Box.tsx
The `React.FC<props>` typing did override the `forwardRef` typing, resulting
in a TS error when trying to pass ref to Box.
=> fix: 🐛 allow ref prop in box component

src/Molecules/DatePicker/Double/Calendar/DoubleCalendar.tsx, src/Molecules/DatePicker/Double/DoubleDatePicker.stories.tsx, src/Molecules/DatePicker/Double/__snapshots__/DoubleDatePicker.stories.storyshot, src/Molecules/DatePicker/__tests__/DoubleDatePicker.test.tsx
Disable the arrow navigation for the double date picker until it has been fully implemented.
Authors: Robin Andersson, Marcus Hogler
=> fix: 🐛 remove unfinished arrow navigation for double datepicker

src/Molecules/DatePicker/shared/dateUtils.ts
we sometime send in `sv-SE` and we need to split it for the datepicker
=> fix: split locale for datepicker

src/Molecules/Timeline/Timeline.stories.tsx, src/Molecules/Timeline/Timeline.tsx, src/Molecules/Timeline/Timeline.types.ts, src/Molecules/Timeline/__snapshots__/Timeline.stories.storyshot
Adding a new status that shows a plain gray circle. This is used for
upcoming events in the timeline. Also extending the date prop to accept
strings. This is also used for upcoming, or ongoing, events where we
don't have a date to show.
=> feat: 🎸 add neutral status to timeline and string type on date

src/Molecules/Input/Select/Select.tsx, src/Molecules/Input/Select/lib/SingleSelectList/SingleSelectList.tsx
clicking the group label with an item in the list selected would cause
all children of the group to become selected
=> fix: 🐛 make options group non-interactive

src/Molecules/Modal/Modal.stories.tsx, src/Molecules/Modal/Modal.types.ts, src/Molecules/Modal/ModalInner.tsx
We need this for when the modal is displayed at the same time as an already existing blocking backdrop.
=> Modal -  make backdrop optional

src/Molecules/Fieldset/__snapshots__/Fieldset.stories.storyshot, src/Molecules/Input/Checkbox/Checkbox.stories.tsx, src/Molecules/Input/Checkbox/Checkbox.tsx, src/Molecules/Input/Checkbox/__snapshots__/Checkbox.stories.storyshot, src/Molecules/Input/Number/Number.stories.tsx, src/Molecules/Input/Number/__snapshots__/Number.stories.storyshot, src/Molecules/Input/Radio/Radio.stories.tsx, src/Molecules/Input/Radio/__snapshots__/Radio.stories.storyshot, src/Molecules/Input/Select/Select.stories.tsx, src/Molecules/Input/Select/__snapshots__/Select.stories.storyshot, src/Molecules/Input/Select/lib/MultiSelectList/__snapshots__/MultiSelectList.stories.storyshot, src/Molecules/Input/Select/lib/wrappers/FormFieldOrFragment.tsx, src/Molecules/Input/Text/Text.stories.tsx, src/Molecules/Input/Text/__snapshots__/Text.stories.storyshot, src/Molecules/Input/Textarea/Textarea.stories.tsx, src/Molecules/Input/Textarea/__snapshots__/Textarea.stories.storyshot
adds stories rendering inputs on a coloured background, adds missing
background style to Checkbox and Select using
theme.color.backgroundInput
=> fix: 🐛 ensure all input types use the correct background color

src/Molecules/Accordion/__snapshots__/Accordion.stories.storyshot, src/Molecules/AccordionItem/AccordionItem.stories.tsx, src/Molecules/AccordionItem/AccordionItem.tsx, src/Molecules/AccordionItem/AccordionItem.types.ts, src/Molecules/AccordionItem/__snapshots__/AccordionItem.stories.storyshot
Adds a prop `withChevron` that uses a chevron to the right instead of a plus/minus to the left as the expand icon in an accordion item. Also allows the title to be a React node instead of only a string.
=> feat: 🎸 add chevron style to accordion item

src/Atoms/Icon/__snapshots__/Icon.stories.storyshot, src/Atoms/Icon/components/Percent.tsx, src/Atoms/Icon/components/Transfer.tsx
Same id was used for the mask element in the Icons Transfer and Percent
=> fix: 🐛 Element id clash in Icons

src/Atoms/Icon/__snapshots__/Icon.stories.storyshot, src/Atoms/Icon/components/Account.tsx, src/Atoms/Icon/components/CalendarO.tsx, src/Atoms/Icon/components/Percent.tsx, src/Atoms/Icon/components/Profile.tsx, src/Atoms/Icon/components/ThreeDotsO.tsx, src/Atoms/Icon/components/Transfer.tsx
affecting icons Account, CalendarO, ThreeDotsO, Percent, Profile,
Transfer
=> fix: 🐛 fix transparent fill on icons

src/Molecules/Input/Select/Select.tsx
When searching options and selecting one of the filtered items, it still selected
from the unfiltered list based on index. This fixes that issue
=> fix: 🐛 select from filtered options instead of all options

src/Molecules/CollapsibleCard/Collapsible.types.ts, src/Molecules/CollapsibleCard/CollapsibleCard.stories.tsx, src/Molecules/CollapsibleCard/CollapsibleCard.tsx, src/Molecules/CollapsibleCard/__snapshots__/CollapsibleCard.stories.storyshot
Add `expandElement`, `titleRowPaddingX` and `titleRowPaddingY` props to CollapsibleCard to make it possible to override the default expand element and title paddings
=> feat: 🎸 add custom expand element and title row padding props to CollapsibleCard

src/Molecules/FlexTable/Row/Row.tsx, src/Molecules/FlexTable/stories/__snapshots__/WithExpandableRows.stories.storyshot, src/Molecules/FlexTable/stories/__snapshots__/WithLotsOfRows.stories.storyshot
A missing `}` in styles for row, caused a syntax error which meant that the styles were not generated correctly. Adding the missing `}` fixed a lot of things
=> fix: 🐛 flextable styling syntax error in row

src/Molecules/PersistentTooltip/PersistentTooltip.stories.tsx, src/Molecules/PersistentTooltip/PersistentTooltip.tsx, src/Molecules/PersistentTooltip/PersistentTooltip.types.ts, src/Molecules/PersistentTooltip/__snapshots__/PersistentTooltip.stories.storyshot, src/Molecules/ShowMoreButton/__snapshots__/ShowMoreButton.stories.storyshot, src/Molecules/Tooltip/Tooltip.tsx, src/Molecules/Tooltip/__snapshots__/Tooltip.stories.storyshot, src/common/PopOver/PopOver.tsx, src/common/PopOver/PopOver.types.ts
ClassName wasn't properly passed through for tooltip components, causing
TS error when trying to style specialized components with
styled-components.
=> fix: 🐛 add classname to persistant tooltip and related comps

src/Molecules/Badge/Badge.md, src/Molecules/Badge/Badge.ts, src/Molecules/Badge/Badge.types.ts, src/Molecules/Badge/components/AccountBadge/AccountBadge.stories.tsx, src/Molecules/Badge/components/AccountBadge/__snapshots__/AccountBadge.stories.storyshot, src/Molecules/Badge/components/IconBadge/IconBadge.stories.tsx, src/Molecules/Badge/components/IconBadge/__snapshots__/IconBadge.stories.storyshot, src/Molecules/Badge/components/LabelBadge/LabelBadge.stories.tsx, src/Molecules/Badge/components/LabelBadge/__snapshots__/LabelBadge.stories.storyshot, src/Molecules/Badge/components/NotificationBadge/NotificationBadge.stories.tsx, src/Molecules/Badge/components/NotificationBadge/__snapshots__/NotificationBadge.stories.storyshot, src/Molecules/Badge/components/StatusBadge/StatusBadge.stories.tsx, src/Molecules/Badge/components/StatusBadge/__snapshots__/StatusBadge.stories.storyshot, src/Molecules/Badge/components/TooltipBadge/TooltipBadge.stories.tsx, src/Molecules/Badge/components/TooltipBadge/__snapshots__/TooltipBadge.stories.storyshot, src/Molecules/Input/Select/Select.stories.tsx
Changed from <Badge.LabelBadge> to <Badge.Label>
co-authors: Anton Bergwall
BREAKING CHANGE: 🧨 Modify Badge sub-component naming convention to use e.g. <Badge.Label>
instead of <Badge.LabelBadge>
=> feat: 🎸 change Badge sub-component naming convention

src/Molecules/TabsNav/TabsNav.tsx, src/Molecules/TabsNav/TabsNav.types.ts
Uses scroll-into-view-if-needed to solve unwanted horizontal scroll on ios browsers
=> fix: 🐛 use scroll-into-view-if-needed to solve bug on ios

src/Molecules/TabsNav/TabsNav.tsx, src/Molecules/TabsNav/TabsNav.types.ts
Uses scrollTo instead of package to calculate scroll destination.
Prevents unwanted scroll to top when interacting with the page where TabsNav is used.
Co-Authors: William Bruce, Robin Andersson
=> fix: 🐛  resolve bug for unwanted scroll to top

src/Molecules/Input/Select/Select.tsx, src/Molecules/Input/Select/__snapshots__/Select.stories.storyshot, src/Molecules/Input/Select/lib/wrappers/FormFieldOrFragment.tsx
Input.Select no longer renders a hidden text input on small screens. On
mobile devices the virtual keyboard would appear and auto focus on the
input element. Also adds TabIndex when noFormField prop is set due to
inconsistent focus and blur behaviors between safari and other browsers.
=> fix: 🐛 don't render hidden search input on mobile screen

src/common/unitUtils.ts, src/index.ts
when consuming the ui librabry, this util abstracts away the need to
call the theme when you need units. Instead of writing ${(theme) =>
theme.spacing.unit(x)}px, you can use the util and write ${units(x)}px;
instead
=> feat: 🎸 add util function to get units

src/Molecules/ProgressIndicator/ProgressIndicator.tsx
Keys should be unique so that components maintain their identity across updates.
=> feat: 🎸 bugfix for progress indicator unique keys

src/Molecules/Modal/Modal.types.ts, src/Molecules/Modal/ModalInner.tsx
Just removes a console.error when performing a tests involving a Modal
=> fix: 🐛 transient props for removing console warnings in test

src/Atoms/DropdownBubble/DropdownBubble.tsx, src/Atoms/DropdownBubble/DropdownBubble.types.ts, src/Molecules/Input/Select/lib/wrappers/FormFieldOrFragment.tsx, src/Molecules/Slider/Slider.tsx, src/theme/theme.ts, src/theme/theme.types.ts
Add 4px border radius to Input.Select and DropdownBubble. Give DropdownBubble a prop for borderRadius since it's used by multiple components with different radius size. Slider tooltip got 2px border radius
=> UC-26: add rounded corners to Dropdowns (Input.Select and DropdownBubble)

src/Molecules/FormField/FormField.stories.tsx, src/Molecules/FormField/FormField.tsx, src/Molecules/FormField/FormField.types.ts, src/Molecules/Input/Checkbox/Checkbox.tsx, src/Molecules/Input/Checkbox/Checkbox.types.ts, src/Molecules/Input/Number/Number.tsx, src/Molecules/Input/Number/Number.types.ts, src/Molecules/Input/Phone/Phone.tsx, src/Molecules/Input/Phone/Phone.types.ts, src/Molecules/Input/Select/Select.tsx, src/Molecules/Input/Select/Select.types.ts, src/Molecules/Input/Select/lib/wrappers/FormFieldOrFragment.tsx, src/Molecules/Input/Text/Text.tsx, src/Molecules/Input/Textarea/Textarea.tsx, src/Molecules/Input/Textarea/Textarea.types.ts
The Tooltip component has a property to indicate if it is being displayed in a modal or not. But when using the tooltip inside the label of an input field this property is not accessible. This makes the tooltip not work when the field is placed in a modal.
=> fix: input field tooltip when in modal

src/Molecules/Button/components/BaseButton/Button.styles.tsx
revert back to old button size when no rounded corners
=> fix: 🐛 revert back to old size when not rounded corners

.husky/commit-msg, package.json, scripts/install-husky.sh, yarn.lock
This is the thing that whips you into writing commit messages in a certain way. This is obsolete when we sqash commits
=> fix: remove commitlint, also now no use for husky

package.json, yarn.lock
=> fix: 🐛 bump to version that supports node ^20

src/Molecules/CoachMarks/Bubble/Bubble.tsx
The bar along with the styling of the bubble card looks a bit wonky in mobile view. (See pics)
This PR fixes this by adding the same border radius as the bar.
Before:
After:
=> fix: use same border radius in mobile as bar

package-lock.json, package.json
This is just some cleanup. lint-staged is not used because we dont hook onto commits anymore since we decided to remove husky
=> chore: remove lint-staged

package-lock.json, package.json
npm uses overrides and not resolutions. It seems that we don't really need these overrides
=> fix: remove package.json resolutions

src/Molecules/FlexTable/Cell/Cell.types.ts, src/Molecules/FlexTable/FlexTable.tsx, src/Molecules/FlexTable/FlexTable.types.ts
Needed to make https://github.com/nordnet/ui/pull/1533 work.
We are currently saying that the Cell component is a `React.FC<Props>` but it's not, there is a react.memo around it. Let's just let Typescript infer what it is, it'capable of doing it without our input
=> fix: stop overriding FlexTable component types

src/Molecules/PersistentTooltip/PersistentTooltip.stories.tsx, src/Molecules/PersistentTooltip/PersistentTooltip.tsx, src/Molecules/PersistentTooltip/PersistentTooltip.types.ts, src/common/PopOver/PopOver.tsx, src/common/PopOver/PopOver.types.ts
Used as 👇 
```ts
// inside some component that uses PersistentTooltip
const updateFnRef = useRef<() => void>();
useEffect(() => {
if (something) {
updateFnRef();
}
}, [something])
const updateCallback = (popperUpdate: () => void) => {
updateFnRef.current = popperUpdate;
};
return (
<PersistentTooltip
isOpen={isOpen}
title="Default persistent tooltip"
description="The tooltip is here.."
closeButtonTitle="Close by clicking X"
onClose={() => setIsOpen(false)}
onPopperMounted={updateCallback}
>
Trigger
</PersistentTooltip>
);
```
=> Add prop onPopperMounted that exposes update function from popper

src/Molecules/PersistentTooltip/PersistentTooltip.stories.tsx, src/Molecules/PersistentTooltip/PersistentTooltip.tsx, src/common/PopOver/index.ts
Aims to fix warning 👇 
```
export 'PopperUpdate' (reexported as 'PopperUpdate') was not found in './PopOver.types' (module has no exports)
```
=> fix: Remove re-export of PopperUpdate from src/common/PopOver/index.ts

src/Atoms/TabTitle/TabTitle.tsx, src/Molecules/Tabs/Tabs.styles.ts, src/Molecules/Tabs/Tabs.tsx, src/Molecules/TabsNav/TabsNav.tsx
Update the design of Tabs - border is no longer a CTA color and it should be bold as inactive as well.
=> UC-152: update the design of Tabs and TabsNav
